# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Use "-" for dividers', max_length=50)),
                ('icon', models.CharField(blank=True, help_text=b'see http://getbootstrap.com/components/#glyphicons-glyphs', max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.MenuItem')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name=b'Date/Time')),
                ('tests', models.IntegerField()),
                ('errors', models.IntegerField()),
                ('failures', models.IntegerField()),
                ('skipped', models.IntegerField(blank=True, null=True)),
                ('modules', models.IntegerField()),
                ('timetaken', models.FloatField(blank=True, null=True)),
                ('installed', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('node', models.CharField(max_length=64)),
                ('system', models.CharField(db_index=True, max_length=16)),
                ('architecture', models.CharField(db_index=True, max_length=16)),
                ('version', models.CharField(db_index=True, max_length=16)),
                ('xml', models.TextField(verbose_name=b'XML Document')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='SelectedNode',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
