# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ci_url',
            field=models.URLField(blank=True, null=True,
                                  verbose_name=b'Continous Integration URL'),
        ),
        migrations.AddField(
            model_name='report',
            name='pr_url',
            field=models.URLField(blank=True, null=True,
                                  verbose_name=b'Pull request URL'),
        ),
    ]
