# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 15:52
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('core', '0002_add_prurl_and_ciurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tags',
            field=taggit.managers.TaggableManager(
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem', to='taggit.Tag',
                verbose_name='Tags'),
        ),
    ]
