# Generated by Django 4.0.1 on 2022-01-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200617_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON document'),
        ),
        migrations.AlterField(
            model_name='report',
            name='xml',
            field=models.TextField(blank=True, null=True, verbose_name='XML document'),
        ),
    ]
