# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-27 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_tags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
            ],
        ),
    ]
