# Generated by Django 4.0.1 on 2022-01-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_json_alter_report_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ciurl',
        ),
    ]
