# Generated by Django 5.2.12 on 2026-03-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_report_ciurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='datetime',
            field=models.DateTimeField(db_index=True, verbose_name='Date/Time'),
        ),
    ]
